import type { ComponentType } from "react";

export type StatementModule = { default: ComponentType };

export const exerciseStatementLoaders: Record<
  string,
  () => Promise<StatementModule>
> = {
  "ex_aluguel_bicicleta": () => import("../../../../../legacy/exercises/all/ex_aluguel_bicicleta.js"),
  "ex_amigo_secreto": () => import("../../../../../legacy/exercises/all/ex_amigo_secreto.js"),
  "ex_aplicacao": () => import("../../../../../legacy/exercises/all/ex_aplicacao.js"),
  "ex_ataque_cardiaco": () => import("../../../../../legacy/exercises/all/ex_ataque_cardiaco.js"),
  "ex_bandeira_do_brasil": () => import("../../../../../legacy/exercises/all/ex_bandeira_do_brasil.js"),
  "ex_baskahra": () => import("../../../../../legacy/exercises/all/ex_baskahra.js"),
  "ex_calculadora": () => import("../../../../../legacy/exercises/all/ex_calculadora.js"),
  "ex_calcular_quadrado": () => import("../../../../../legacy/exercises/all/ex_calcular_quadrado.js"),
  "ex_canhao": () => import("../../../../../legacy/exercises/all/ex_canhao.js"),
  "ex_castigo": () => import("../../../../../legacy/exercises/all/ex_castigo.js"),
  "ex_cateto_adjacente": () => import("../../../../../legacy/exercises/all/ex_cateto_adjacente.js"),
  "ex_cateto_oposto": () => import("../../../../../legacy/exercises/all/ex_cateto_oposto.js"),
  "ex_chocolate": () => import("../../../../../legacy/exercises/all/ex_chocolate.js"),
  "ex_circunferencia": () => import("../../../../../legacy/exercises/all/ex_circunferencia.js"),
  "ex_codigo_secreto": () => import("../../../../../legacy/exercises/all/ex_codigo_secreto.js"),
  "ex_combustivel_moto": () => import("../../../../../legacy/exercises/all/ex_combustivel_moto.js"),
  "ex_comparador_numeros": () => import("../../../../../legacy/exercises/all/ex_comparador_numeros.js"),
  "ex_condominio": () => import("../../../../../legacy/exercises/all/ex_condominio.js"),
  "ex_contar_ocorrencia": () => import("../../../../../legacy/exercises/all/ex_contar_ocorrencia.js"),
  "ex_cor_carro": () => import("../../../../../legacy/exercises/all/ex_cor_carro.js"),
  "ex_corredor": () => import("../../../../../legacy/exercises/all/ex_corredor.js"),
  "ex_criptomoedas": () => import("../../../../../legacy/exercises/all/ex_criptomoedas.js"),
  "ex_decoracao_cilindro": () => import("../../../../../legacy/exercises/all/ex_decoracao_cilindro.js"),
  "ex_disciplinas": () => import("../../../../../legacy/exercises/all/ex_disciplinas.js"),
  "ex_distancia_praia": () => import("../../../../../legacy/exercises/all/ex_distancia_praia.js"),
  "ex_docentes": () => import("../../../../../legacy/exercises/all/ex_docentes.js"),
  "ex_fatorial": () => import("../../../../../legacy/exercises/all/ex_fatorial.js"),
  "ex_fibonnaci": () => import("../../../../../legacy/exercises/all/ex_fibonnaci.js"),
  "ex_filtrar_elementos": () => import("../../../../../legacy/exercises/all/ex_filtrar_elementos.js"),
  "ex_financiamento": () => import("../../../../../legacy/exercises/all/ex_financiamento.js"),
  "ex_hotel": () => import("../../../../../legacy/exercises/all/ex_hotel.js"),
  "ex_imc": () => import("../../../../../legacy/exercises/all/ex_imc.js"),
  "ex_imposto_renda": () => import("../../../../../legacy/exercises/all/ex_imposto_renda.js"),
  "ex_interclasses": () => import("../../../../../legacy/exercises/all/ex_interclasses.js"),
  "ex_inverter": () => import("../../../../../legacy/exercises/all/ex_inverter.js"),
  "ex_investimento": () => import("../../../../../legacy/exercises/all/ex_investimento.js"),
  "ex_jovens_trabalhadores": () => import("../../../../../legacy/exercises/all/ex_jovens_trabalhadores.js"),
  "ex_juros_compostos": () => import("../../../../../legacy/exercises/all/ex_juros_compostos.js"),
  "ex_juros_simples": () => import("../../../../../legacy/exercises/all/ex_juros_simples.js"),
  "ex_lucro_ou_prejuizo": () => import("../../../../../legacy/exercises/all/ex_lucro_ou_prejuizo.js"),
  "ex_maior_3": () => import("../../../../../legacy/exercises/all/ex_maior_3.js"),
  "ex_media_2": () => import("../../../../../legacy/exercises/all/ex_media_2.js"),
  "ex_media_ponderada": () => import("../../../../../legacy/exercises/all/ex_media_ponderada.js"),
  "ex_media_simples": () => import("../../../../../legacy/exercises/all/ex_media_simples.js"),
  "ex_miniatura_trofeu": () => import("../../../../../legacy/exercises/all/ex_miniatura_trofeu.js"),
  "ex_moedas": () => import("../../../../../legacy/exercises/all/ex_moedas.js"),
  "ex_movimento_retilineo": () => import("../../../../../legacy/exercises/all/ex_movimento_retilineo.js"),
  "ex_museu": () => import("../../../../../legacy/exercises/all/ex_museu.js"),
  "ex_num_divisiveis": () => import("../../../../../legacy/exercises/all/ex_num_divisiveis.js"),
  "ex_obter_maior": () => import("../../../../../legacy/exercises/all/ex_obter_maior.js"),
  "ex_obter_media": () => import("../../../../../legacy/exercises/all/ex_obter_media.js"),
  "ex_ola_mundo": () => import("../../../../../legacy/exercises/all/ex_ola_mundo.js"),
  "ex_onibus_vs_bicicleta": () => import("../../../../../legacy/exercises/all/ex_onibus_vs_bicicleta.js"),
  "ex_palindromo": () => import("../../../../../legacy/exercises/all/ex_palindromo.js"),
  "ex_papel": () => import("../../../../../legacy/exercises/all/ex_papel.js"),
  "ex_par_ou_impar": () => import("../../../../../legacy/exercises/all/ex_par_ou_impar.js"),
  "ex_pergolado": () => import("../../../../../legacy/exercises/all/ex_pergolado.js"),
  "ex_pesquisa_satisfacao": () => import("../../../../../legacy/exercises/all/ex_pesquisa_satisfacao.js"),
  "ex_pneu": () => import("../../../../../legacy/exercises/all/ex_pneu.js"),
  "ex_ponto_quadrado": () => import("../../../../../legacy/exercises/all/ex_ponto_quadrado.js"),
  "ex_por_extenso": () => import("../../../../../legacy/exercises/all/ex_por_extenso.js"),
  "ex_porcelanato": () => import("../../../../../legacy/exercises/all/ex_porcelanato.js"),
  "ex_positivo_negativo": () => import("../../../../../legacy/exercises/all/ex_positivo_negativo.js"),
  "ex_postes": () => import("../../../../../legacy/exercises/all/ex_postes.js"),
  "ex_potencia_2": () => import("../../../../../legacy/exercises/all/ex_potencia_2.js"),
  "ex_poupanca_vs_cdb": () => import("../../../../../legacy/exercises/all/ex_poupanca_vs_cdb.js"),
  "ex_prestacao_imovel": () => import("../../../../../legacy/exercises/all/ex_prestacao_imovel.js"),
  "ex_primo": () => import("../../../../../legacy/exercises/all/ex_primo.js"),
  "ex_produto_simples": () => import("../../../../../legacy/exercises/all/ex_produto_simples.js"),
  "ex_radio": () => import("../../../../../legacy/exercises/all/ex_radio.js"),
  "ex_recipiente": () => import("../../../../../legacy/exercises/all/ex_recipiente.js"),
  "ex_reducao_mesada": () => import("../../../../../legacy/exercises/all/ex_reducao_mesada.js"),
  "ex_residuo": () => import("../../../../../legacy/exercises/all/ex_residuo.js"),
  "ex_restituição": () => import("../../../../../legacy/exercises/all/ex_restituição.js"),
  "ex_satelite": () => import("../../../../../legacy/exercises/all/ex_satelite.js"),
  "ex_seguranca_balada": () => import("../../../../../legacy/exercises/all/ex_seguranca_balada.js"),
  "ex_senha": () => import("../../../../../legacy/exercises/all/ex_senha.js"),
  "ex_sistema_irrigacao": () => import("../../../../../legacy/exercises/all/ex_sistema_irrigacao.js"),
  "ex_soma_pares": () => import("../../../../../legacy/exercises/all/ex_soma_pares.js"),
  "ex_soma_positivos": () => import("../../../../../legacy/exercises/all/ex_soma_positivos.js"),
  "ex_soma_simples": () => import("../../../../../legacy/exercises/all/ex_soma_simples.js"),
  "ex_soma_termos": () => import("../../../../../legacy/exercises/all/ex_soma_termos.js"),
  "ex_somar_elementos": () => import("../../../../../legacy/exercises/all/ex_somar_elementos.js"),
  "ex_sorteio_viagem": () => import("../../../../../legacy/exercises/all/ex_sorteio_viagem.js"),
  "ex_substituir": () => import("../../../../../legacy/exercises/all/ex_substituir.js"),
  "ex_tabuada": () => import("../../../../../legacy/exercises/all/ex_tabuada.js"),
  "ex_temperatura": () => import("../../../../../legacy/exercises/all/ex_temperatura.js"),
  "ex_terreno": () => import("../../../../../legacy/exercises/all/ex_terreno.js"),
  "ex_tipos_triangulo": () => import("../../../../../legacy/exercises/all/ex_tipos_triangulo.js"),
  "ex_torneira": () => import("../../../../../legacy/exercises/all/ex_torneira.js"),
  "ex_volei": () => import("../../../../../legacy/exercises/all/ex_volei.js"),
};

export function hasJsStatement(id: string): boolean {
  return id in exerciseStatementLoaders;
}
