import type { ComponentType } from "react";

export type LessonModule = { default: ComponentType };

export const lessonLoaders: Record<string, () => Promise<LessonModule>> = {
  "unity-0-1": () => import("../../../../../legacy/classes/all/unity-0-1.js"),
  "unity-1-1": () => import("../../../../../legacy/classes/all/unity-1-1.js"),
  "unity-1-2": () => import("../../../../../legacy/classes/all/unity-1-2.js"),
  "unity-1-3": () => import("../../../../../legacy/classes/all/unity-1-3.js"),
  "unity-1-4": () => import("../../../../../legacy/classes/all/unity-1-4.js"),
  "unity-1-5": () => import("../../../../../legacy/classes/all/unity-1-5.js"),
  "unity-1-6": () => import("../../../../../legacy/classes/all/unity-1-6.js"),
  "unity-1-7": () => import("../../../../../legacy/classes/all/unity-1-7.js"),
  "unity-1-8": () => import("../../../../../legacy/classes/all/unity-1-8.js"),
  "unity-10-1": () => import("../../../../../legacy/classes/all/unity-10-1.js"),
  "unity-10-2": () => import("../../../../../legacy/classes/all/unity-10-2.js"),
  "unity-10-3": () => import("../../../../../legacy/classes/all/unity-10-3.js"),
  "unity-11-1": () => import("../../../../../legacy/classes/all/unity-11-1.js"),
  "unity-11-2": () => import("../../../../../legacy/classes/all/unity-11-2.js"),
  "unity-11-3": () => import("../../../../../legacy/classes/all/unity-11-3.js"),
  "unity-11-4": () => import("../../../../../legacy/classes/all/unity-11-4.js"),
  "unity-11-5": () => import("../../../../../legacy/classes/all/unity-11-5.js"),
  "unity-2-1": () => import("../../../../../legacy/classes/all/unity-2-1.js"),
  "unity-2-2": () => import("../../../../../legacy/classes/all/unity-2-2.js"),
  "unity-2-3": () => import("../../../../../legacy/classes/all/unity-2-3.js"),
  "unity-2-4": () => import("../../../../../legacy/classes/all/unity-2-4.js"),
  "unity-2-5": () => import("../../../../../legacy/classes/all/unity-2-5.js"),
  "unity-3-1": () => import("../../../../../legacy/classes/all/unity-3-1.js"),
  "unity-3-2": () => import("../../../../../legacy/classes/all/unity-3-2.js"),
  "unity-3-3": () => import("../../../../../legacy/classes/all/unity-3-3.js"),
  "unity-3-4": () => import("../../../../../legacy/classes/all/unity-3-4.js"),
  "unity-3-5": () => import("../../../../../legacy/classes/all/unity-3-5.js"),
  "unity-4-1": () => import("../../../../../legacy/classes/all/unity-4-1.js"),
  "unity-4-2": () => import("../../../../../legacy/classes/all/unity-4-2.js"),
  "unity-4-3": () => import("../../../../../legacy/classes/all/unity-4-3.js"),
  "unity-5-1": () => import("../../../../../legacy/classes/all/unity-5-1.js"),
  "unity-5-2": () => import("../../../../../legacy/classes/all/unity-5-2.js"),
  "unity-5-3": () => import("../../../../../legacy/classes/all/unity-5-3.js"),
  "unity-5-4": () => import("../../../../../legacy/classes/all/unity-5-4.js"),
  "unity-6-1": () => import("../../../../../legacy/classes/all/unity-6-1.js"),
  "unity-6-2": () => import("../../../../../legacy/classes/all/unity-6-2.js"),
  "unity-6-3": () => import("../../../../../legacy/classes/all/unity-6-3.js"),
  "unity-6-4": () => import("../../../../../legacy/classes/all/unity-6-4.js"),
  "unity-7-1": () => import("../../../../../legacy/classes/all/unity-7-1.js"),
  "unity-7-2": () => import("../../../../../legacy/classes/all/unity-7-2.js"),
  "unity-7-3": () => import("../../../../../legacy/classes/all/unity-7-3.js"),
  "unity-7-4": () => import("../../../../../legacy/classes/all/unity-7-4.js"),
  "unity-8-1": () => import("../../../../../legacy/classes/all/unity-8-1.js"),
  "unity-8-2": () => import("../../../../../legacy/classes/all/unity-8-2.js"),
  "unity-8-3": () => import("../../../../../legacy/classes/all/unity-8-3.js"),
  "unity-9-1": () => import("../../../../../legacy/classes/all/unity-9-1.js"),
  "unity-9-2": () => import("../../../../../legacy/classes/all/unity-9-2.js"),
  "unity-9-3": () => import("../../../../../legacy/classes/all/unity-9-3.js"),
};
