exports.data = {
    "ex_ola_mundo": "programming",
    "ex_soma_simples" : "programming",
    "ex_produto_simples" : "programming",
    "ex_media_simples" : "programming",
    "ex_circunferencia" : "programming",
    "ex_media_ponderada" : "programming",
    "ex_imc": "programming",
    "ex_criptomoedas": "programming",
    "ex_temperatura": "programming",
    "ex_movimento_retilineo" : "programming",
    "ex_seguranca_balada" : "programming",
    "ex_comparador_numeros" : "programming",
    "ex_positivo_negativo" : "programming",
    "ex_par_ou_impar" : "programming",
    "ex_lucro_ou_prejuizo" : "programming",
    "ex_calculadora" : "programming",
    "ex_media_2" : "programming",
    "ex_maior_3" : "programming",
    "ex_soma_positivos" : "programming",
    "ex_por_extenso" : "programming",
    "ex_tipos_triangulo" : "programming",
    "ex_ponto_quadrado" : "programming",
    "ex_sistema_irrigacao" : "programming",
    "ex_ataque_cardiaco" : "programming",
    "ex_potencia_2" : "programming",
    "ex_soma_pares" : "programming",
    "ex_num_divisiveis" : "programming",
    "ex_castigo" : "programming",
    "ex_fibonnaci" : "programming",
    "ex_tabuada" : "programming",
    "ex_primo" : "programming",
    "ex_miniatura_trofeu" : "arithmetic",
    "ex_combustivel_moto" :"arithmetic",
    "ex_onibus_vs_bicicleta": "arithmetic",
    "ex_bandeira_do_brasil": "arithmetic",
    "ex_porcelanato": "arithmetic",
    "ex_jovens_trabalhadores": "arithmetic",
    "ex_pesquisa_satisfacao": "arithmetic",
    "ex_recipiente": "arithmetic",
    "ex_reducao_mesada": "arithmetic",
    "ex_baskahra": "functions",
    "ex_disciplinas": "functions",
    "ex_aluguel_bicicleta": "functions",
    "ex_pneu": "functions",
    "ex_chocolate": "functions",
    "ex_canhao": "functions",
    "ex_docentes": "probability",
    "ex_moedas": "probability",
    "ex_restituição": "probability",
    "ex_sorteio_viagem": "probability",
    "ex_cor_carro": "probability",
    "ex_imposto_renda": "probability",
    "ex_amigo_secreto": "probability",
    "ex_soma_termos" : "progression",
    "ex_corredor" : "progression",
    "ex_residuo" : "progression",
    "ex_codigo_secreto" : "progression",
    "ex_papel" : "progression",
    "ex_torneira" : "progression",
    "ex_juros_simples" : "financial",
    "ex_juros_compostos" : "financial",
    "ex_aplicacao" : "financial",
    "ex_prestacao_imovel" : "financial",
    "ex_investimento" : "financial",
    "ex_poupanca_vs_cdb" : "financial",
    "ex_cateto_oposto" : "financial",
    "ex_cateto_adjacente" : "financial",
    "ex_satelite" : "trigonometry",
    "ex_pergolado" : "trigonometry",
    "ex_terreno" : "trigonometry",
    "ex_cateto_oposto" : "trigonometry",
    "ex_cateto_adjacente" : "trigonometry",
    "ex_decoracao_cilindro" : "trigonometry",
    "ex_distancia_praia" : "trigonometry",
    "ex_condominio" : "combinatorics",
    "ex_hotel" : "combinatorics",
    "ex_radio" : "combinatorics",
    "ex_volei" : "combinatorics",
    "ex_museu" : "combinatorics",
    "ex_senha" : "combinatorics",
    "ex_interclasses" : "combinatorics",
    "ex_fatorial" : "combinatorics",
}