exports.data = {
    "ex_ola_mundo": "programming",
    "ex_soma_simples" : "programming",
    "ex_produto_simples" : "programming",
    "ex_media_simples" : "programming",
    "ex_circunferencia" : "programming",
    "ex_media_ponderada" : "programming",
    "ex_imc": "programming",
    "ex_criptomoedas": "programming",
    "ex_temperatura": "programming",
    "ex_movimento_retilineo" : "programming",
    "ex_seguranca_balada" : "programming",
    "ex_comparador_numeros" : "programming",
    "ex_positivo_negativo" : "programming",
    "ex_par_ou_impar" : "programming",
    "ex_lucro_ou_prejuizo" : "programming",
    "ex_calculadora" : "programming",
    "ex_media_2" : "programming",
    "ex_maior_3" : "programming",
    "ex_soma_positivos" : "programming",
    "ex_por_extenso" : "programming",
    "ex_tipos_triangulo" : "programming",
    "ex_ponto_quadrado" : "programming",
    "ex_sistema_irrigacao" : "programming",
    "ex_ataque_cardiaco" : "programming",
    "ex_potencia_2" : "programming",
    "ex_soma_pares" : "programming",
    "ex_num_divisiveis" : "programming",
    "ex_castigo" : "programming",
    "ex_fibonnaci" : "programming",
    "ex_tabuada" : "programming",
    "ex_primo" : "programming",
    "ex_miniatura_trofeu" : "arithmetic",
    "ex_combustivel_moto" :"arithmetic",
    "ex_onibus_vs_bicicleta": "arithmetic",
    "ex_bandeira_do_brasil": "arithmetic",
    "ex_porcelanato": "arithmetic",
    "ex_jovens_trabalhadores": "arithmetic",
    "ex_pesquisa_satisfacao": "arithmetic",
    "ex_recipiente": "arithmetic",
    "ex_reducao_mesada": "arithmetic"
}